/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExcelToSQL;

import org.junit.Test;

import jp.co.softventure.smartec.excel2ddl.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
