/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.co.softventure.smartec.excel2ddl;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
